### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by henry8th** [blockfrost/blockfrost-python#1]
Hi hope your well,

I have an api key generated for the testnet.. how do i send a request to the testnet using this lib?

Thanks

**Comment by mathiasfrohlich** [comment]
Thanks for reaching out.  

I can see that this is not yet documented.   
Thanks for bringing this to my attention.  

If you import the `ApiUrls` the urls are presented there for you, the code simply defaults to `mainnet`.  
But this can be overwritten by passing the `testnet.value` to base_url.  

See code example below:   

```python
from blockfrost import BlockFrostApi, ApiUrls

api = BlockFrostApi(
    base_url=ApiUrls.testnet.value,
    project_id='YOUR API KEY HERE'  # or export environment variable BLOCKFROST_PROJECT_ID
)

health = api.health()
print(health.is_healthy) # True
```

**Comment by henry8th** [comment]
Thank you.. your response is appreciated :)
