### ISSUE TITLE
No matching distribution found for blockfrost-python

### ISSUE THREAD

**Issue by tars01** [blockfrost/blockfrost-python#15]
I'm having an issue installing via pip. I have tried different machines but it's the same issues. 

Tried Python 3.6.8 and 3.6.9.

Any assistance appreciated. 

```
(development_env) root@tars:~$ pip install blockfrost-python
Collecting blockfrost-python
  Could not find a version that satisfies the requirement blockfrost-python (from versions: )
No matching distribution found for blockfrost-python
```

**Comment by mathiasfrohlich** [comment]
@tars01 Thanks for reaching out.  

Python 3.6 has exceeded end life support.

So this package has been configured with `Requires: Python >=3.7, <4`.  
That is why a version for 3.6 is not showing.  
I will highly suggest you upgrade your python version, to a version that receives security fixes.

Hope this clears up the issue you encountered.

**Comment by mathiasfrohlich** [comment]
You are welcome. 
I will close this issue, feel free to reach out if you encounter any other issues.
