### ISSUE TITLE
Local docker instance

### ISSUE THREAD

**Issue by martap79** [blockfrost/blockfrost-python#28]
Can this module be used with a local docker instance of blockfrost?
changing the base_url variable doesn't seem to do the job. Looks like api_version (v0) is added to the url. this breaks connectivity to a local instance.

**Comment by martap79** [comment]
setting env var `BLOCKFROST_API_VERSION="."` works around the issue.

**Comment by sorki** [comment]
Solved in master, will be included in next release.

**Comment by slowbackspace** [comment]
this should be resolved now, closing the issue.
