### ISSUE TITLE
Package for 0.6.0 hasn't been released

### ISSUE THREAD

**Issue by ross-spencer** [blockfrost/blockfrost-python#41]
Is there any reason [0.6.0](https://github.com/blockfrost/blockfrost-python/releases/tag/0.6.0) (Nov '23) hasn't been released to PyPi?

PyPi currently showing 0.5.3: https://pypi.org/project/blockfrost-python/

**Comment by cffls** [comment]
@mmahut @slowbackspace   Could you please take a look at this? Thanks!

**Comment by ross-spencer** [comment]
just checking in on whether there is an update on this? (or if there are any issues preventing this at all?)

**Comment by slowbackspace** [comment]
Hi, sorry about this. We've been dealing with some issues with PyPI and have been working with their support to get it sorted out.
Version 0.6.0 is out now! https://pypi.org/project/blockfrost-python/0.6.0/

**Comment by ross-spencer** [comment]
no worries! thanks @slowbackspace this is awesome! much appreciated.
