### ISSUE TITLE
address_utxos object missing #tx_index

### ISSUE THREAD

**Issue by luisg707** [blockfrost/blockfrost-python#6]
Traceback (most recent call last):
  File , line 31, in <module>
    server_utxo.check_for_transactions()
  File "", line 26, in check_for_transactions
    all_utxos = self.api.address_utxos(address=self.server_wallet)
  File "/site-packages/blockfrost/utils.py", line 108, in pagination
    return [object_class(**o) for o in request_json]
  File "/env/lib/python3.9/site-packages/blockfrost/utils.py", line 108, in <listcomp>
    **return [object_class(**o) for o in request_json]**
**TypeError: __init__() got an unexpected keyword argument 'tx_index'**

```python
all_utxos = self.api.address_utxos(address=self.server_wallet)

```

Using return_type 'json' works fine, but would love to use native python

**Comment by luisg707** [comment]
Also, I am using 0.3.1

**Comment by luisg707** [comment]
❯ pip install blockfrost-python==0.3.1
Requirement already satisfied: blockfrost-python==0.3.1 in ./env/lib/python3.9/site-packages (0.3.1)

**Comment by luisg707** [comment]
```python
class AddressesUTXOSResponse:
    @dataclass
    class Amount:
        unit: str
        quantity: str

    tx_hash: str
    **tx_index: str**
    output_index: int
    amount: [Amount]
    block: str
    data_hash: str

    def __init__(self, tx_hash: str, output_index: int, **tx_index: int**, amount: [Amount], block: str, data_hash: str) -> None:
        self.tx_hash = tx_hash
        **self.tx_index = tx_index**
        self.output_index = output_index
        self.amount = [self.Amount(**o) for o in amount]
        self.block = block
        self.data_hash = data_hash

```

I fixed this by adding tx_index: int. your docs say it's depreciated, but your API is still sending that val?

**Comment by mathiasfrohlich** [comment]
@luisg707  Thanks for bringing this to my attention.
Also thanks for looking deep into this issue and providing a solution.

You have the option to call the API calls with parameter return_type='json' to circumvent the object mapping.

The tx_index is documented as an `integer`.

Would you share the address you used? 
So that I may use it for testing making sure it will work.

**Comment by luisg707** [comment]
Hey @mathiasfrohlich  When are you going to fix this? I am using your code for a few production deployments and for each server that I import your project on, I have to manually fix the library.

Can you make a new release? 

Also address, do you mean the cardano address?

**Comment by mathiasfrohlich** [comment]
@luisg707 Thanks for your help in raising this issue.  
A fix is now live.
https://pypi.org/project/blockfrost-python/0.3.2/
